// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// onigmo_init
void onigmo_init();
RcppExport SEXP _stringore_onigmo_init() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    onigmo_init();
    return R_NilValue;
END_RCPP
}
// onigmo_cleanup
void onigmo_cleanup();
RcppExport SEXP _stringore_onigmo_cleanup() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    onigmo_cleanup();
    return R_NilValue;
END_RCPP
}
// onigomo_library_version
std::string onigomo_library_version();
RcppExport SEXP _stringore_onigomo_library_version() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(onigomo_library_version());
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_stringore_onigmo_init", (DL_FUNC) &_stringore_onigmo_init, 0},
    {"_stringore_onigmo_cleanup", (DL_FUNC) &_stringore_onigmo_cleanup, 0},
    {"_stringore_onigomo_library_version", (DL_FUNC) &_stringore_onigomo_library_version, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_stringore(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
