# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

onigmo_init <- function() {
    invisible(.Call(`_stringore_onigmo_init`))
}

onigmo_cleanup <- function() {
    invisible(.Call(`_stringore_onigmo_cleanup`))
}

#' Return the version of the Onigmo library being used by the package
#'
#' @export
#' @examples
#' onigomo_library_version()
onigomo_library_version <- function() {
    .Call(`_stringore_onigomo_library_version`)
}

